#!/usr/bin/env bash
# This script displays numbers from 1 to 100

for ((i=1; i<=100; i++));
do
	fizzBuzz=$((i%15))
	fizz=$((i%3))
	buzz=$((i%5))
	if [ $fizzBuzz -eq 0 ]; then
	       echo "FizzBuzz"
	elif [ $fizz -eq 0 ]; then
	       echo "Fizz"
	elif [ $buzz -eq 0 ]; then
	       echo "Buzz"
	else
		echo $i
	fi
done