#!/usr/bin/env bash
# This script displays "Best School" 10
# but in the 9th iteration print "hi" after it

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]; then
       echo "Hi"
    fi
    ((i+=1))
done
