#!/usr/bin/env bash
# This script displays "Best School" 10
# but in the 9th iteration print "hi" after it

i=1

while [ $i -le 20 ]
do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((i+=1))
done
