#!/usr/bin/env bash

FILENAME="school"

if [ -e $FILENAME ]; then
     	echo "school file exists"

	if [ -s $FILENAME ]; then
	     	echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $FILENAME ]; then
	     	echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi