#!/usr/bin/env bash
# Script that configures localhost's and facebook.com's IP addresses in the hosts file

cp /etc/hosts hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' hosts.new
sed -i '/^127.0.0.2/a\8.8.8.8\t\tfacebook.com' hosts.new
cp hosts.new /etc/hosts
